### ISSUE TITLE
Uncaught Error: Cannot decorate a destroyed marker

### ISSUE THREAD

**Issue by rtk4** [msafi/inline-markdown-images#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: [inline-markdown-images](https://github.com/some-atom/inline-markdown-images) package 1.0.0

### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At C:\Users\rkendall\AppData\Local\atom\app-1.18.0\resources\app\src\decoration-manager.js:204

Error: Cannot decorate a destroyed marker
    at DecorationManager.module.exports.DecorationManager.decorateMarker (~/AppData/Local/atom/app-1.18.0/resources/app/src/decoration-manager.js:194:23)
    at TextEditor.module.exports.TextEditor.decorateMarker (~/AppData/Local/atom/app-1.18.0/resources/app/src/text-editor.js:1737:43)
    at /packages/inline-markdown-images/index.js:57:23
    at /packages/inline-markdown-images/index.js:57:106
    at ForwardsMultiLine.iterate (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/text-buffer/lib/match-iterator.js:263:15)
    at TextBuffer.module.exports.TextBuffer.scanInRange (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/text-buffer/lib/text-buffer.js:982:29)
    at TextBuffer.module.exports.TextBuffer.scan (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/text-buffer/lib/text-buffer.js:935:25)
    at TextEditor.module.exports.TextEditor.scan (~/AppData/Local/atom/app-1.18.0/resources/app/src/text-editor.js:2685:32)
    at processTextBuffer (/packages/inline-markdown-images/index.js:34:19)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/text-buffer/lib/text-buffer.js:1442:31
```

### Commands

```
     -6:27 pane:show-next-item (input.hidden-input)
     -6:26 core:save (input.hidden-input)
     -6:22.2.0 pane:split-right-and-copy-active-item (input.hidden-input)
  2x -6:21.1.0 core:move-right (input.hidden-input)
     -6:20.3.0 core:move-left (input.hidden-input)
     -6:17.1.0 core:undo (input.hidden-input)
     -6:13.6.0 core:backspace (input.hidden-input)
     -6:11.8.0 pane:split-right-and-copy-active-item (input.hidden-input)
  5x -4:07.3.0 core:move-up (input.hidden-input)
 21x -4:01.9.0 core:move-down (input.hidden-input)
 18x -0:20.8.0 core:move-up (input.hidden-input)
  6x -0:18.1.0 core:move-down (input.hidden-input)
     -0:17 core:move-up (input.hidden-input)
  3x -0:16.5.0 editor:move-line-up (input.hidden-input)
     -0:15.6.0 editor:move-line-down (input.hidden-input)
     -0:07.2.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.0 
atom-shortcuts 0.0.2 
autocomplete-json 5.5.0 
autocomplete-paths 1.0.5 
colorful-json 1.1.0 
flatten-json 0.1.5 
highlight-selected 0.13.1 
inline-markdown-images 1.0.0 
json-colorer 1.0.0 
json-converter 0.2.4 
json-schema 0.1.15 
keyboard-scroll 0.7.0 
markdown-folder 0.5.0 
markdown-image-helper 1.0.4 
markdown-pdf 1.5.4 
markdown-preview-plus 2.4.9 
markdown-scroll-sync 2.1.2 
markdown-toc 0.4.2 
minimap 4.28.2 
minimap-highlight-selected 4.6.1 
pretty-json 1.6.3 
todo-show 1.11.0 
uuidgen 1.2.1 
```

**Comment by msafi** [comment]
I'm not sure what's happening here.
