### ISSUE TITLE
Failed to activate the inline-markdown-images package

### ISSUE THREAD

**Issue by aali101** [msafi/inline-markdown-images#4]
[Enter steps to reproduce:]

1. ...Open ATOM
2. ...The error in the image appears
![inline error](https://user-images.githubusercontent.com/37799490/43050358-45a97f56-8dff-11e8-8969-b167cd1d3946.jpg)

**Atom**: 1.28.2 x64
**Electron**: 2.0.5
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [inline-markdown-images](https://github.com/some-atom/inline-markdown-images) package 1.3.0

### Stack Trace

Failed to activate the inline-markdown-images package

```
At Cannot read property 'start' of undefined

TypeError: Cannot read property 'start' of undefined
    at Function.module.exports.Range.fromObject (~/AppData/Local/atom/app-1.28.2/resources/app/node_modules/text-buffer/lib/range.js:33:38)
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.markBufferRange (~/AppData/Local/atom/app-1.28.2/resources/app/node_modules/text-buffer/lib/display-marker-layer.js:104:33)
    at TextEditor.markBufferRange (~/AppData/Local/atom/app-1.28.2/resources/app/src/text-editor.js:2424:42)
    at /packages/inline-markdown-images/index.js:46:31
    at /packages/inline-markdown-images/index.js:57:106
    at TextBuffer.module.exports.TextBuffer.scanInRange (~/AppData/Local/atom/app-1.28.2/resources/app/node_modules/text-buffer/lib/text-buffer.js:1118:15)
    at TextBuffer.module.exports.TextBuffer.scan (~/AppData/Local/atom/app-1.28.2/resources/app/node_modules/text-buffer/lib/text-buffer.js:1073:25)
    at TextEditor.scan (~/AppData/Local/atom/app-1.28.2/resources/app/src/text-editor.js:3530:30)
    at Object.processTextBuffer (/packages/inline-markdown-images/index.js:34:19)
    at /packages/inline-markdown-images/index.js:66:14
    at Workspace.observeTextEditors (~/AppData/Local/atom/app-1.28.2/resources/app/src/workspace.js:639:59)
    at Object.activate (/packages/inline-markdown-images/index.js:63:20)
    at Package.activateNow (~/AppData/Local/atom/app-1.28.2/resources/app/src/package.js:230:33)
    at measure (~/AppData/Local/atom/app-1.28.2/resources/app/src/package.js:206:33)
    at Package.measure (~/AppData/Local/atom/app-1.28.2/resources/app/src/package.js:88:25)
    at activationPromise.Promise (~/AppData/Local/atom/app-1.28.2/resources/app/src/package.js:200:20)
    at new Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.28.2/resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.28.2/resources/app/src/package-manager.js:695:42)
    at config.transactAsync (~/AppData/Local/atom/app-1.28.2/resources/app/src/package-manager.js:670:36)
    at Config.transactAsync (~/AppData/Local/atom/app-1.28.2/resources/app/src/config.js:866:28)
    at PackageManager.activatePackages (~/AppData/Local/atom/app-1.28.2/resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (~/AppData/Local/atom/app-1.28.2/resources/app/src/package-manager.js:647:50)
    at loadStatePromise.loadState.then (~/AppData/Local/atom/app-1.28.2/resources/app/src/atom-environment.js:871:27)
    at <anonymous>
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.32.5 
atom-image-resize 0.3.0 
city-lights-syntax 1.1.8 
emmet 2.4.3 
file-icons 2.1.22 
highlight-selected 0.14.0 
html-to-css 0.2.2 
hugo-theme-learn 0.0.0 
hugofy 2.0.0 
inline-markdown-images 1.3.0 
insert-img 0.1.4 
markdown-image-paste 2.5.2 
my-package 0.0.0 
pandoc-convert 1.1.1 
pigments 0.40.2 
sass-autocompile 0.13.5 
teletype 0.13.3 
todo 0.6.0 
```

**Comment by msafi** [comment]
Fixed
